name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run docker image
        run: docker build -t kevariable/frontend-gh-actions -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true kevariable/frontend-gh-actions npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-gh
          environment_name: Docker-gh-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-494628114799
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
